apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-collector
spec:
  selector:
    matchLabels:
      app: ebpf-collector
  template:
    metadata:
      labels:
        app: ebpf-collector
    spec:
      hostPID: true
      dnsPolicy: ClusterFirst
      containers:
        - name: collector
          image: michaelzheng67/ebpf-collector:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: bpffs
              mountPath: /sys/fs/bpf
            - name: modules
              mountPath: /lib/modules
            - name: debugfs
              mountPath: /sys/kernel/debug
      volumes:
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
        - name: modules
          hostPath:
            path: /lib/modules
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
