apiVersion: v1
kind: Pod
metadata:
  name: curl-spammer
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          echo "Sending curl...";
          curl -v http://example.com;
          sleep 5;
          done
